### ISSUE TITLE
onChange callback in Tabs component misses second parameter.

### ISSUE THREAD

**Issue by fhammerschmidt** [jsiebern/reason-mui-binding-generator#1]
Currently, it is not possible to use the generated bindings with the Tabs component, as the `onChange` signature only includes the first param (`event`) and not the second one (`value`).

See https://material-ui-next.com/api/tabs/

By the way, Bucklescript 3 got rid of Js.boolean, we can now directly use bool instead.

**Comment by jsiebern** [comment]
Hey, thanks for the hint! I need to add those special cases manually, I'll update in a bit!

**Comment by jsiebern** [comment]
@fhammerschmidt Can you upgrade to @next and lmk if all works as expected :-)?

**Comment by fhammerschmidt** [comment]
Wow! Thanks for your fast response!

My road was a bit bumpy, I probably did something wrong with the paths, but yes it works with MUI v1.0.0-beta.41 at least!
There were some major path changes in v1.0.0-beta.42/43 so I assume you have do adapt your scripts to that.

Also, it would be nice if the `theme` prop was an option on the Tabs (and probably some other components).

**Comment by jsiebern** [comment]
That is weird, it works fine on `v1.0.0-beta43` for me! What exactly didn't work for you? About the theme: Yeah, there's still some quirks and things missing here and there :)

**Comment by fhammerschmidt** [comment]
Which MuiPath did you provide? The root of `material-ui` or `material-ui/packages/material-ui`? I used the former and it did not work because it did not find `getStylesCreator`.

**Comment by jsiebern** [comment]
Ah sorry, I thought you meant something went wrong actually using the dist package (https://github.com/jsiebern/bs-material-ui). The new path is `material-ui/packages/material-ui`!
