### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by InsidersByte** [jsiebern/reason-mui-binding-generator#2]
Hi,

Great work on this project! :+1: 

I wanted to use this issue to discuss my thoughts from using this generate to generate the bindings for [bs-material-ui](https://github.com/InsidersByte/bs-material-ui/pull/55/files).

### Missing Props

* missing the style prop on every component (I have done this, will link to pr soon)
* colSpan missing on TableRow (I have done this, will link to pr soon)
* TableRow missing onDoubleClick (I have done this, will link to pr soon)

### Errors
* theme is required when it shouldn't be (Drawer, Menu, etc.)
* TablePagination onChangeRowsPerPage, onChangePage and labelDisplayedRows incorrect  (I have done this, will link to pr soon)
* Checkbox onChange incorrect  (I have done this, will link to pr soon)

### Suggestions

* change _ from prepend to append as prepend compiler warnings are ignored
* improve types of unwrapValue (I have done this, will link to pr soon)
* upgrade to bs-platform@3.0.0 (I have done this, will link to pr soon)

**Comment by jsiebern** [comment]
Hi, great input, thank you! Looking forward to those PRs :-) I built another generator in the meantime, which is a lot cleaner and more adaptable (https://github.com/jsiebern/reason-devextreme-reactive-generator) Maybe I'll switch that out soon if I can figure out the best way to get the types from Typesript afterall.

**Comment by jsiebern** [comment]
Hey, I just pushed an update to the generator which fixes most of the issues you mentioned I believe.
I converted it from my other generator project as that one is a lot more structured and easier to modify.

**Fixes include:**
- Most of the before incorrect [`onChange`](https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi.re#L1837) things should be fixed as it derives function types from the description now if it can
- [`TableRow`](https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi.re#L8896)/ [`TableCell`](https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi.re#L8625)
- Added the `style` prop to all components (I was thinking about also adding `id`, do you think that makes any sense?)
- Refined the [`TablePagination`](https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi.re#L8698) props
- `theme` props are [optional](https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi.re#L2218)

I believe that my generator appends `_` as well, maybe you can check the examples you had in mind? Also, what improvements did you implement for the `unwrapValue`? 

I'm sorry that this made some of your planned PRs unnecessary but I thought I'd better do this now than later as this generator code is much easier to extend and work with.
