### ISSUE TITLE
reason-react 0.4.0 compatibility

### ISSUE THREAD

**Issue by cknitt** [jsiebern/reason-mui-binding-generator#3]
From the reason-react 0.4.0 release notes:

> Remove ReasonReact.Callback module (undocumented and unused).

Therefore `ReasonReact.Callback.t` is no longer available, so

```reason
ReasonReact.Callback.t(ReactEventRe.Synthetic.t)
```

needs to become

```reason
(ReactEventRe.Synthetic.t => unit)
```

etc.

**Comment by jsiebern** [comment]
Wow, you were quick, I'll push an update soon 😉

**Comment by jsiebern** [comment]
Updated it, should be fine and all but I still published to @next as I haven't had the chance to test the release myself properly, feedback would be appreciated :-)

**Comment by cknitt** [comment]
Thanks a lot! The generated code is not correct though.

E.g.
```reason
      ~onChange: ReasonReact.Callback.t(ReactEventRe.Form.t)=?,
```
is now
```reason
      ~onChange: ReactEventRe.Form.t=?,
```
but should be
```reason
      ~onChange: ReactEventRe.Form.t => unit=?,
```

**Comment by jsiebern** [comment]
Uuuhm, yes 😅 it seems I’m quite tired today 😂 I’ll fix it tomorrow morning, sorry, my bad!

**Comment by jsiebern** [comment]
Pushed an update that should fix it

**Comment by cknitt** [comment]
Great, thanks! It works fine now. :-)

BTW, it seems that the last bindings were not generated from the v1.0.0-beta.43 tag in the material-ui repo, but from master (slightly newer - `focusVisible` was added in the meantime).

I regenerated the bindings from the v1.0.0-beta.43 tag with working callback definitions and will send you a PR.

**Comment by jsiebern** [comment]
Closing as this issue is fixed
