### ISSUE TITLE
Setting things up locally

### ISSUE THREAD

**Issue by PTaylour** [jsiebern/reason-mui-binding-generator#4]
Apologies if this isn't the best place for a setup question.

I'm trying to run the script locally so I can have a go at finishing the theme, but, haven't quite got it working.

### Couple of questions

Is the env file used at the moment?

- https://github.com/jsiebern/reason-mui-binding-generator/blob/master/extract/src/env.js

or is are these the only place where I need to point at my clone of the core material-ui package? 

- https://github.com/jsiebern/reason-mui-binding-generator/blob/9d094a499ec8f215515cd45dc8b17ab0c75d8cdc/extract/package.json#L50

- https://github.com/jsiebern/reason-mui-binding-generator/blob/master/extract/src/extract.js#L7-L9

### An error message

Updating those ^ I get a parsing error in `ButtonBase`

```
Error parsing src for /path/to/reason-mui-binding-generator/extract/core/ButtonBase/TouchRipple.js
/path/to/workspace/reason-mui-binding-generator/extract/src/extract.js:65
    throw err;
    ^

SyntaxError: Unexpected token (168:46)
```

**Comment by jsiebern** [comment]
@PTaylour Hi! Yeah, sorry, the error message in Button Base... Extracting is somewhat flaky, I always have to remove the `**` in the Mui code by hand as `babel-runtime` for some reason does not transform them :-( I haven't had the time to get it working as it doesn't seem worth the effort 😂 

The env file is no longer in use, the flow basically goes like this:

```
/* Replace the path in the copy command in extract/package.json */
cd extract
yarn copy
yarn extract
cd ..
yarn parse
```

Sorry about the mess, extracting the info from the Mui code base has always been shaky for me, so I tend to fix a few things as I go for a new release here and there

**Comment by jsiebern** [comment]
Can this issue be closed for now then?

**Comment by PTaylour** [comment]
Haven't tried it yet, but you instructions look good :) I'll re-open if I run into any more problems :)
